project:
  info:
    version: "0.0.1-SNAPSHOT"
    name: "Model Management"
    description: "This service provides the list of models an advisor is authorized to use for its clients and keeps track of model usage."

spring:
  datasource:
    url: jdbc:postgresql://${DB_URI}:5432/model_db
    username: ${DB_USER:model}
    password: ${DB_USER_PASSWD:password}
    
  cloud:
    stream:
      function:
        definition: handleAccountCreation
      kafka:
        bindings:
          handleAccountCreation-in-0:
            consumer:
              enableDlq: true
              dlqName: model-events-dlq
      bindings:
        handleAccountCreation-in-0:
          destination: Account.events
          group: "${spring.application.name}"
        accountCreationFailure-in-0:
          destination: custodian.failure.event
          group: "${spring.application.name}"
